/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__WIFI_POINT

#include <WiFi.h>

// RemoteXY connection settings
#define REMOTEXY_WIFI_SSID "RemoteXY"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377


#include <RemoteXY.h>

// RemoteXY GUI configuration
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =  // 55 bytes V19
  { 255, 5, 0, 0, 0, 48, 0, 19, 0, 0, 0, 0, 31, 1, 200, 84, 1, 1, 3, 0,
    5, 7, 12, 60, 60, 32, 2, 26, 31, 5, 127, 11, 60, 60, 32, 2, 26, 31, 2, 74,
    11, 44, 22, 0, 2, 26, 31, 31, 79, 78, 0, 79, 70, 70, 0 };

// this structure defines all the variables and events of your control interface
struct {

  // input variables
  int8_t joystick_01_x;  // from -100 to 100
  int8_t joystick_01_y;  // from -100 to 100
  int8_t joystick_02_x;  // from -100 to 100
  int8_t joystick_02_y;  // from -100 to 100
  uint8_t switch_01;     // =1 if switch ON and =0 if OFF, from 0 to 1

  // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////



#include <ESP32Servo.h>
Servo servo1, servo2, servo3, servo4;


void setup() {
  RemoteXY_Init();  // initialization by macros

  pinMode(D2, OUTPUT);
  pinMode(D3, OUTPUT);
  pinMode(D4, OUTPUT);
  pinMode(D5, OUTPUT);
  pinMode(D6, OUTPUT);
  pinMode(D7, OUTPUT);

  servo1.attach(D8);
  servo2.attach(D9);
  servo3.attach(D10);
  servo4.attach(D11);

  servo1.write(90);
  servo2.write(90);
  servo3.write(90);
  servo4.write(90);

  RemoteXYEngine.delay(500);
  // TODO you setup code
}
void ileriGit(int hiz) {
  digitalWrite(D4, 1);
  digitalWrite(D5, 0);

  digitalWrite(D6, 1);
  digitalWrite(D7, 0);

  analogWrite(D2, hiz);
  analogWrite(D3, hiz);
}
void geriGit(int hiz) {
  digitalWrite(D4, 0);
  digitalWrite(D5, 1);

  digitalWrite(D6, 0);
  digitalWrite(D7, 1);

  analogWrite(D2, hiz);
  analogWrite(D3, hiz);
}
void sagGit(int hiz) {
  digitalWrite(D4, 1);
  digitalWrite(D5, 0);

  digitalWrite(D6, 0);
  digitalWrite(D7, 1);

  analogWrite(D2, hiz);
  analogWrite(D3, hiz);
}
void solGit(int hiz) {
  digitalWrite(D4, 0);
  digitalWrite(D5, 1);

  digitalWrite(D6, 1);
  digitalWrite(D7, 0);

  analogWrite(D2, hiz);
  analogWrite(D3, hiz);
}
void fren() {
  digitalWrite(D4, 0);
  digitalWrite(D5, 0);

  digitalWrite(D6, 0);
  digitalWrite(D7, 0);

  analogWrite(D2, 0);
  analogWrite(D3, 0);
}
void loop() {
  RemoteXYEngine.handler();


  if (RemoteXY.joystick_01_y > 10) {
    int motorIleri = map(RemoteXY.joystick_01_y, 0, 100, 0, 255);
    ileriGit(motorIleri);
  } else if (RemoteXY.joystick_01_y < -10) {
    int motorGeri = map((RemoteXY.joystick_01_y * (-1)), 0, 100, 0, 255);
    geriGit(motorGeri);
  } else if (RemoteXY.joystick_01_x < -10) {
    int motorSol = map((RemoteXY.joystick_01_x * (-1)), 0, 100, 0, 255);
    solGit(motorSol);
  } else if (RemoteXY.joystick_01_x > 10) {
    int motorSag = map(RemoteXY.joystick_01_x, 0, 100, 0, 255);
    sagGit(motorSag);
  } else {
    fren();
  }


  int servoX = map(RemoteXY.joystick_02_x, -100, 100, 0, 179);
  servo1.write(servoX);
  int servoIleri = map(RemoteXY.joystick_02_y, -100, 100, 0, 179);
  servo2.write(servoIleri);
  servoIleri -= 15;
  if (servoIleri < 0) {
    servoIleri = 0;
  } else if (servoIleri > 179) {
    servoIleri = 179;
  }
  servo3.write(servoIleri);

  if (RemoteXY.switch_01 == 1) {
    servo4.write(30);
  } else {
    servo4.write(120);
  }


  RemoteXYEngine.delay(80);
}
